version: '3.8'
services:
  client:
    user: root
    container_name: client-dev
    image: client-dev:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
  server:
    user: root
    container_name: server-dev
    image: server-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5005:5005"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development







